<script setup>
import { Head, Link, useForm } from "@inertiajs/vue3";

import MainLayout from "@/Layouts/MainLayout.vue";

import AppPageHeader from "@/Components/Page/AppPageHeader.vue";
import AppPageToolbar from "@/Components/Page/AppPageToolbar.vue";
import AppPageCard from "@/Components/Page/AppPageCard.vue";

import AppFormSection from "@/Components/Form/AppFormSection.vue";
import AppFormField from "@/Components/Form/AppFormField.vue";
import AppFormActions from "@/Components/Form/AppFormActions.vue";

import Button from "primevue/button";
import Select from "primevue/select";
import DatePicker from "primevue/datepicker";
import Divider from "primevue/divider";
import Tag from "primevue/tag";

defineOptions({
    layout: MainLayout,
});

const props = defineProps({
    cities: {
        type: Array,
        default: () => [],
    },

    destinations: {
        type: Array,
        default: () => [],
    },

    analysisResult: {
        type: Object,
        default: null,
    },
});

const form = useForm({
    origin_city_id: null,
    destination_id: null,
    departure_date: null,
    departure_time: null,
});

function analyze() {
    form.post(route("travel-analysis.analyze"));
}
</script>

<template>
    <Head title="Travel Analysis" />

    <div class="space-y-6">
        <AppPageHeader
            title="Travel Analysis"
            description="Analyze your travel before making a booking."
        />

        <AppPageCard>
            <form @submit.prevent="analyze">
                <AppFormSection
                    title="Travel Information"
                    description="Select your travel information."
                >
                    <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
                        <AppFormField
                            label="Origin City"
                            :error="form.errors.origin_city_id"
                            required
                        >
                            <Select
                                v-model="form.origin_city_id"
                                :options="cities"
                                optionLabel="name"
                                optionValue="id"
                                placeholder="Select Origin City"
                                fluid
                            />
                        </AppFormField>

                        <AppFormField
                            label="Destination"
                            :error="form.errors.destination_id"
                            required
                        >
                            <Select
                                v-model="form.destination_id"
                                :options="destinations"
                                optionLabel="name"
                                optionValue="id"
                                placeholder="Select Destination"
                                fluid
                            />
                        </AppFormField>

                        <AppFormField
                            label="Departure Date"
                            :error="form.errors.departure_date"
                            required
                        >
                            <DatePicker
                                v-model="form.departure_date"
                                dateFormat="yy-mm-dd"
                                showIcon
                                fluid
                            />
                        </AppFormField>

                        <AppFormField
                            label="Departure Time"
                            :error="form.errors.departure_time"
                            required
                        >
                            <DatePicker
                                v-model="form.departure_time"
                                timeOnly
                                hourFormat="24"
                                showIcon
                                fluid
                            />
                        </AppFormField>
                    </div>
                </AppFormSection>

                <AppFormActions>
                    <Button
                        type="submit"
                        label="Analyze Travel"
                        icon="pi pi-search"
                        :loading="form.processing"
                    />
                </AppFormActions>
            </form>
        </AppPageCard>

        <AppPageCard v-if="analysisResult">
            <AppFormSection
                title="Analysis Result"
                description="Travel estimation generated by the system."
            >
                <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
                    <div>
                        <div class="text-sm text-gray-500">Distance</div>

                        <div class="text-lg font-semibold">
                            {{ analysisResult.distance }}
                        </div>
                    </div>

                    <div>
                        <div class="text-sm text-gray-500">
                            Estimated Duration
                        </div>

                        <div class="text-lg font-semibold">
                            {{ analysisResult.estimated_duration }}
                        </div>
                    </div>

                    <div>
                        <div class="text-sm text-gray-500">Estimated Price</div>

                        <div class="text-lg font-semibold">
                            {{ analysisResult.price }}
                        </div>
                    </div>

                    <div>
                        <div class="text-sm text-gray-500">Weather</div>

                        <Tag :value="analysisResult.weather" />
                    </div>

                    <div>
                        <div class="text-sm text-gray-500">Reward</div>

                        <Tag
                            :value="analysisResult.reward"
                            severity="success"
                        />
                    </div>

                    <div
                        v-if="analysisResult.recommendation"
                        class="md:col-span-2"
                    >
                        <div class="text-sm text-gray-500">Recommendation</div>

                        <div class="mt-2">
                            {{ analysisResult.recommendation }}
                        </div>
                    </div>
                </div>

                <Divider />

                <div class="flex justify-end">
                    <Link
                        :href="
                            route('bookings.create', {
                                origin_city_id: form.origin_city_id,
                                destination_id: form.destination_id,
                                departure_date: form.departure_date,
                                departure_time: form.departure_time,
                                distance: analysisResult.distance,
                                estimated_duration:
                                    analysisResult.estimated_duration,
                                price: analysisResult.price,
                            })
                        "
                    >
                        <Button
                            label="Continue to Booking"
                            icon="pi pi-arrow-right"
                            severity="success"
                        />
                    </Link>
                </div>
            </AppFormSection>
        </AppPageCard>
    </div>
</template>
